#!/usr/bin/env bash

set -eu -o pipefail

mail=${MAILDIR:-$HOME/mail}

find -L "$mail" -mindepth 1 \
    -type d \( \
        -name '.*' -o \
        -name '\[Gmail\]*' -o \
        -path "$mail/lkml" -o \
        -path "$mail/main/shelve" -o \
        -path "$mail/news" -o \
    -false \) -prune -o -type d ! -iregex '.*/\(cur\|new\|tmp\)$' -print0 |
    sort -z |
    while read -r -d '' mb; do
        printf 'mailboxes %q\n' "$mb"
done
