#!/usr/bin/env bash

set -e

hc() { herbstclient "$@"; }

hc emit_hook reload


# Key bindings
# ----------------------------------------

hc keyunbind --all

Mod=Mod4

# Basic
hc keybind $Mod-q reload
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-c close

# Basic movement
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# Moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# Splitting frames
hc keybind $Mod-backslash split right 0.5
hc keybind $Mod-minus split bottom 0.5
hc keybind $Mod-Control-space split explode

# Resizing frames
resize_step=0.05
hc keybind $Mod-Control-h resize left +$resize_step
hc keybind $Mod-Control-j resize down +$resize_step
hc keybind $Mod-Control-k resize up +$resize_step
hc keybind $Mod-Control-l resize right +$resize_step

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Layouting
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-Shift-space set_layout horizontal
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-t pseudotile toggle
hc keybind $Mod-r remove

# Focus
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-bracketright cycle +1
hc keybind $Mod-bracketleft cycle -1
hc keybind $Mod-BackSpace jumpto urgent

# Screens & Workspaces
hc keybind $Mod-w focus_monitor -l
hc keybind $Mod-e focus_monitor -r
hc keybind $Mod-Shift-w shift_to_monitor -l
hc keybind $Mod-Shift-e shift_to_monitor -r

hc keybind $Mod-d use_index +1 --skip-visible # misssing --skip-empty
hc keybind $Mod-s use_index -1 --skip-visible # missing --skip-empty

hc keybind $Mod-u focus_monitor 0
hc keybind $Mod-i focus_monitor 1
hc keybind $Mod-o focus_monitor 2
hc keybind $Mod-Shift-u shift_to_monitor 0
hc keybind $Mod-Shift-i shift_to_monitor 1
hc keybind $Mod-Shift-o shift_to_monitor 2

hc keybind $Mod-a use_previous

# Launchers
hc keybind $Mod-p spawn dmenu_run
hc keybind $Mod-Shift-Return spawn term

# Screenshots
hc keybind $Mod-Print spawn sshot
hc keybind $Mod-Shift-Print spawn sshot -s

# Audio
hc keybind $Mod-Shift-bracketright spawn audio playback_up
hc keybind $Mod-Shift-bracketleft spawn audio playback_down
hc keybind $Mod-Shift-m spawn audio playback_toggle
hc keybind $Mod-Shift-n spawn audio playback_dock_toggle
hc keybind $Mod-Shift-r spawn audio capture_toggle

# XKB
hc keybind $Mod-F1 spawn xkb us
hc keybind $Mod-F2 spawn xkb sk
hc keybind $Mod-F3 spawn xkb cz

# Other
hc keybind $Mod-F9 spawn bash -c 'xscreen0 && herbstclient reload'
hc keybind $Mod-F10 spawn bash -c 'xscreen && herbstclient reload'
hc keybind $Mod-Shift-F10 spawn bash -c 'xscreen-mobile && herbstclient reload'
hc keybind $Mod-F12 spawn bash -c 'grabc 2>&1 | clipi'
hc keybind $Mod-Shift-F12 spawn bash -c 'xmeasure | clipi'
hc keybind $Mod-Shift-b spawn backlight-toggle


# Mouse
# ----------------------------------------

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


# Other
# ----------------------------------------

# Theme
hc attr theme.reset 1
hc attr theme.floating.reset 1
hc attr theme.tiling.reset 1
hc attr theme.background_color red
hc attr theme.border_width 1
hc attr theme.active.color '#9fbc00'
hc attr theme.urgent.color orange

hc set always_show_frame 1
hc set focus_follows_mouse 1
hc set frame_bg_active_color '#97bc00'
hc set frame_bg_normal_color '#222'
hc set frame_bg_transparent 1
hc set frame_border_normal_color '#111' # read by panel
hc set frame_border_width 0
hc set frame_transparent_width 1
hc set mouse_recenter_gap 50
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set tree_style '╾│ ├└╼─┐'
hc set update_dragged_clients 1
hc set window_gap 0
hc set wmname LG3D

# Rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Monitors
hc set_monitors $(hc disjoin_rects $(hc detect_monitors -l | sort -t + -k2,2))

hc unlock

# Find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done
