#!/usr/bin/env bash

set -eu -o pipefail

from_git() {
    set -eu
    local name=$1
    shift
    printf '\n> %s\n' "$name"
    if cd "$name" &>/dev/null; then
        git update
    else
        git clone --recursive --single-branch "$@" "$name"
    fi
}
export -f from_git

cd ~/.vim

mkdir -p pack/custom/opt
cd pack/custom/opt

grep -vxE '\s*|(\s*#.*)' <<-EOF | parallel --colsep \\t+ --bar from_git

	ansiesc				https://github.com/jakar/vim-AnsiEsc
	colorschemes		https://github.com/flazz/vim-colorschemes
	enhanced-diff		https://github.com/chrisbra/vim-diff-enhanced
	gnupg				https://github.com/jamessan/vim-gnupg

	bufexplorer			https://github.com/jlanzarotta/bufexplorer
	dirvish				https://github.com/justinmk/vim-dirvish
	easy-align			https://github.com/junegunn/vim-easy-align
	easymotion			https://github.com/easymotion/vim-easymotion
	emmet				https://github.com/mattn/emmet-vim
	fugitive			https://github.com/tpope/vim-fugitive
	fzf-ext				https://github.com/junegunn/fzf.vim
	goyo				https://github.com/junegunn/goyo.vim
	limelight			https://github.com/junegunn/limelight.vim
	nerdtree			https://github.com/scrooloose/nerdtree
	repeat				https://github.com/tpope/vim-repeat
	speeddating			https://github.com/tpope/vim-speeddating
	surround			https://github.com/tpope/vim-surround
	tagbar				https://github.com/majutsushi/tagbar
	tcomment			https://github.com/tomtom/tcomment_vim
	ultisnips			https://github.com/SirVer/ultisnips
	undotree			https://github.com/mbbill/undotree
	unimpaired			https://github.com/tpope/vim-unimpaired
	vim-snippets		https://github.com/honza/vim-snippets
	visualrepeat		https://github.com/vim-scripts/visualrepeat

	ale					https://github.com/w0rp/ale
	deoplete			https://github.com/Shougo/deoplete.nvim
	neomake				https://github.com/neomake/neomake

EOF
echo
