#!/usr/bin/env bash

set -eu -o pipefail

from_git() {
    set -eu
    local name=$1
    shift
    printf '\n> %s\n' "$name"
    if cd "$name" &>/dev/null; then
        git update
    else
        git clone --recursive --single-branch "$@" "$name"
    fi
}
export -f from_git

cd ~/.vim

mkdir -p pack/custom/opt
cd pack/custom/opt

grep -vxE '\s*|(\s*#.*)' <<-EOF | parallel --colsep \\t+ --bar from_git

	ale					https://github.com/dense-analysis/ale
	ansiesc				https://github.com/jakar/vim-AnsiEsc
	bufexplorer			https://github.com/jlanzarotta/bufexplorer
	coc					https://github.com/neoclide/coc.nvim
	colorschemes		https://github.com/flazz/vim-colorschemes
	ctrlp				https://github.com/ctrlpvim/ctrlp.vim
	dirvish				https://github.com/justinmk/vim-dirvish
	easy-align			https://github.com/junegunn/vim-easy-align
	easymotion			https://github.com/easymotion/vim-easymotion
	emmet				https://github.com/mattn/emmet-vim
	fugitive			https://github.com/tpope/vim-fugitive
	fzf-ext				https://github.com/junegunn/fzf.vim
	gnupg				https://github.com/jamessan/vim-gnupg
	goyo				https://github.com/junegunn/goyo.vim
	limelight			https://github.com/junegunn/limelight.vim
	neomake				https://github.com/neomake/neomake
	nerdtree			https://github.com/preservim/nerdtree
	repeat				https://github.com/tpope/vim-repeat
	speeddating			https://github.com/tpope/vim-speeddating
	surround			https://github.com/tpope/vim-surround
	tagbar				https://github.com/majutsushi/tagbar
	tcomment			https://github.com/tomtom/tcomment_vim
	ultisnips			https://github.com/SirVer/ultisnips
	undotree			https://github.com/mbbill/undotree
	unimpaired			https://github.com/tpope/vim-unimpaired
	vim-snippets		https://github.com/honza/vim-snippets
	visualrepeat		https://github.com/inkarkat/vim-visualrepeat

EOF
echo
