#!/usr/bin/env bash

set -eu

# See also:
#
#   https://wiki.termux.com/wiki/Special:AllPages
#   https://wiki.termux.com/wiki/Switching_package_manager
#
#   termux-am
#   termux-chroot
#   termux-dialog
#   termux-fingerprint
#   termux-help
#   termux-info
#   termux-reload-settings
#   termux-reset

termux-change-repo
termux-setup-storage

pkg update
pkg upgrade

pkg install x11-repo
pkg install \
    bsdtar \
    busybox \
    file \
    fzf \
    git \
    htop \
    iproute2 \
    jq \
    linux-man-pages \
    man \
    ncurses-utils \
    neovim \
    openssh \
    openssl-tool \
    parallel \
    ranger \
    ripgrep \
    runit \
    socat \
    termux-api \
    tmux \
    tree \
    vim \
    weechat \
    weechat-perl-plugin \
    weechat-python-plugin \
    zsh
