#!/usr/bin/env bash

set -eu

prgname=${0##*/}

(( $# )) || set -- default

if [[ $1 = -* ]]; then
    echo "usage: $prgname [runlevel]"
    exit 0
fi

cd ~/.termux

lvl_new=$1
[[ -d svdir.$lvl_new ]] || {
    printf 'no such runlevel: %s\n' "$lvl_new" >&2
    exit 1
}
ln -snf svdir."$lvl_new" svdir
printf 'runlevel: %s\n' "$lvl_new" >&2

runsvdir=$(command -v runsvdir)
start-stop-daemon \
    --start --exec "$runsvdir" \
    --pidfile "$XDG_RUNTIME_DIR/$prgname.pid" \
    --background --output "$PWD/$prgname.out" \
    --chdir "$PWD" --make-pidfile \
    --oknodo --verbose \
    svdir >&2
