#!/usr/bin/env bash

set -eu

cd "${BASH_SOURCE%/*}" || exit 1

install -m 700 -D -d sandbox

ln -sf -t sandbox \
    ../common.conf \
    ../dirmngr.conf \
    ../gpg-agent.conf \
    ../gpg.conf \
    ../scdaemon.conf
