[theme]
theme = "native"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#c0c0c0"
info_bg = "#000000"
info_fg = "#c0c0c0"
good_bg = "#000000"
good_fg = "#efefef"
warning_bg  = "#000000"
warning_fg  = "#feed6a"
critical_bg = "#000000"
critical_fg = "#ff6666"
separator = ""
separator_bg = "#000000"
separator_fg = "#c0c0c0"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_w:100) |"
[block.theme_overrides]
idle_fg = "#efefef"

[[block]]
block = "cpu"
format = " $icon $utilization.eng(pad_with:0) "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(pad_with:0) "

[[block]]
block = "backlight"
cycle = [5, 40, 70, 100]
device = "acpi_video0"
format = " $icon $brightness "
invert_icons = true

[[block]]
block = "sound"
format = " $icon $volume "
show_volume_when_muted = true

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a❘%d.%m❘%H:%M') "
interval = 60
