#!/usr/bin/env bash

set -eu

cd "${BASH_SOURCE%/*}"

(( $EUID )) && odir="$PWD" || odir='/etc/terminfo'

while IFS= read -d $'\0' entry; do
    printf -- '-> %s\n' "$entry"
    tic -o "$odir" "$entry"
done < <(
    find -maxdepth 1 -type f \
        ! -executable \
        ! -name '.gitignore' \
        -printf '%f\0' | sort -z
)
