#!/usr/bin/env bash

set -eu -o pipefail

cd "${BASH_SOURCE%/*}"

(( EUID )) && odir=$PWD || odir='/etc/terminfo'

find . -maxdepth 1 -type f \
    ! -executable \
    ! -name '.gitignore' \
    -printf '%f\0' | sort -z |
    while IFS= read -rd $'\0' entry; do
        printf -- '-> %s\n' "$entry"
        tic -a -o "$odir" "$entry"
    done
