#!/usr/bin/env bash

set -eu

targetdir="$HOME/.local/share/fonts"

readonly tmpdir=$(mktemp -d)
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

cd "$tmpdir"

get() {
    local fname
    fname=$(curl -sLfJO -w '%{filename_effective}' "$1")
    unzip -qq "$fname" -d out
    find out -iregex '.*\.\(ttf\|otf\)' -exec mv {} "$targetdir" \;
    rm -rf out
}

get http://www.fontsquirrel.com/fonts/download/Anonymous
get http://www.fontsquirrel.com/fonts/download/BPmono
get http://www.fontsquirrel.com/fonts/download/MonospaceTypewriter
get http://www.fontsquirrel.com/fonts/download/cuprum
get http://www.fontsquirrel.com/fonts/download/jura1
get http://www.fontsquirrel.com/fonts/download/lekton
get http://www.fontsquirrel.com/fonts/download/oxygen-mono
get http://www.fontsquirrel.com/fonts/download/pt-mono
