#!/usr/bin/env bash

set -eu

odir="$HOME/.local/share/fonts"

tmpdir=$(mktemp -d)
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

cd "$tmpdir"

from_zip() {
    local fname
    fname=$(curl -sLfJO -w '%{filename_effective}' "$1")
    unzip -qq "$fname" -d out
    find out -iregex '.*\.\(ttf\|otf\)' -exec mv {} "$odir" \;
    rm -rf out
}

from_zip http://www.fontsquirrel.com/fonts/download/Anonymous
from_zip http://www.fontsquirrel.com/fonts/download/BPmono
from_zip http://www.fontsquirrel.com/fonts/download/MonospaceTypewriter
from_zip http://www.fontsquirrel.com/fonts/download/cuprum
from_zip http://www.fontsquirrel.com/fonts/download/jura1
from_zip http://www.fontsquirrel.com/fonts/download/lekton
from_zip http://www.fontsquirrel.com/fonts/download/oxygen-mono
from_zip http://www.fontsquirrel.com/fonts/download/pt-mono
