#!/usr/bin/env bash

set -eu

export fdir="$HOME/.local/share/fonts"

tmpdir=$(mktemp -d)
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

cd "$tmpdir"

from_zip() {
    local furl=$1 fname odir
    fname=$(curl -sLfJO -w '%{filename_effective}' "$furl")
    odir=$(md5sum <<<"$fname" | awk '{print $1}')
    unzip -qq "$fname" -d "$odir"
    find "$odir" -iregex '.*\.\(ttf\|otf\)' -exec mv {} "$fdir" \;
}
export -f from_zip

parallel from_zip <<-EOF
	http://www.fontsquirrel.com/fonts/download/Anonymous
	http://www.fontsquirrel.com/fonts/download/BPmono
	http://www.fontsquirrel.com/fonts/download/MonospaceTypewriter
	http://www.fontsquirrel.com/fonts/download/cuprum
	http://www.fontsquirrel.com/fonts/download/jura1
	http://www.fontsquirrel.com/fonts/download/lekton
	http://www.fontsquirrel.com/fonts/download/oxygen-mono
	http://www.fontsquirrel.com/fonts/download/pt-mono
EOF
