#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}" || exit 1

from_git() {
    set -u
    printf '\n> %s\n' "$1"
    if cd "$1" &>/dev/null; then
        git update
    else
        git clone-shallow "${@:2}" "$1"
    fi
}
export -f from_git

echo
confirm 'zsh plugins?' n && {
    grep -vxE '\s*|(\s*#.*)' <<-EOF | parallel --colsep \\s+ --bar from_git
		zsh-autosuggestions             https://github.com/zsh-users/zsh-autosuggestions
		zsh-completions                 https://github.com/zsh-users/zsh-completions
		zsh-history-substring-search    https://github.com/zsh-users/zsh-history-substring-search
		zsh-syntax-highlighting         https://github.com/zsh-users/zsh-syntax-highlighting
	EOF
}
echo
